// MEDIA OS · РЕЕСТР БРЕНДОВ И ПЛОЩАДОК — единый источник для панели Центра.
// Источник правды: утверждён основателем 02.08 (бренд-архитектура + ownership matrix).
// Правила: URL/handle не выдумываются (preferred handle помечен в notes);
// НИКАКИХ секретов — только булево hasAccess и ИМЯ env-переменной в apiKeyEnvName.
// status — строго: Confirmed | Needs Verification | Planned | Not Registered | Not Needed.
// Обновление данных = правка этого файла через ветку→PR→деплой (dataAsOf поднимать!).

export const DATA_AS_OF = '2026-08-03'

const A = 'Andrej' // Access Owner везде основатель; регистрации/OAuth делает только он

export const ACCOUNTS = [
  { brand: 'Berg Finance', platform: 'Website', region: 'Global', language: 'ru+en', handle: null,
    url: 'https://berg.finance/landing', status: 'Confirmed', purpose: 'хаб-лендинг, BERG, white-label',
    formats: 'страницы, transparency', accessOwner: A, hasAccess: true, apiKeyEnvName: null,
    priority: 'high', automationStatus: 'manual', apiStatus: 'none',
    nextAction: 'исполнение аудита 02.08 (правовые страницы — первоочередное)',
    notes: 'аудит: .claude/marketing/audit-berg-finance-2026-08-02.md; пуш = сразу прод' },
  { brand: 'Andrej AI', platform: 'LinkedIn', region: 'Global', language: 'en', handle: 'bergandrej',
    url: 'https://www.linkedin.com/in/bergandrej/', status: 'Confirmed', purpose: 'деловой личный бренд',
    formats: 'посты 1000–1500 зн.', accessOwner: A, hasAccess: true, apiKeyEnvName: null,
    priority: 'high', automationStatus: 'manual', apiStatus: 'none', nextAction: 'контент-план после карты', notes: null },
  { brand: 'Berg Finance', platform: 'X', region: 'Global', language: 'en', handle: 'bergfinance',
    url: 'https://x.com/bergfinance', status: 'Confirmed', purpose: 'профессиональный DeFi-контур',
    formats: 'треды 5–8×270', accessOwner: A, hasAccess: true, apiKeyEnvName: null,
    priority: 'high', automationStatus: 'manual', apiStatus: 'none',
    nextAction: 'решение по Blotato', notes: 'прямой X API не покупаем (красная линия)' },
  { brand: 'Berg Mindset', platform: 'Instagram', region: 'Global', language: 'ru+en', handle: 'thebergmindset',
    url: 'https://www.instagram.com/thebergmindset/', status: 'Confirmed', purpose: 'личность, визуал',
    formats: '300–600 зн. + 5 визуалов, Reels', accessOwner: A, hasAccess: true, apiKeyEnvName: null,
    priority: 'medium', automationStatus: 'manual', apiStatus: 'none', nextAction: null, notes: null },
  { brand: 'YLDX AI', platform: 'Telegram', region: 'RU', language: 'ru', handle: '@YLDXMAIN',
    url: 'https://t.me/YLDXMAIN', status: 'Confirmed', purpose: 'корпоративный канал YLDX (закреплено 02.08)',
    formats: 'посты 600–900 зн.', accessOwner: A, hasAccess: true, apiKeyEnvName: 'REVIEW_BOT_TOKEN',
    priority: 'live', automationStatus: 'button', apiStatus: 'live',
    nextAction: 'назначить @BergAlertsbot админом канала; 4 поста ждут кнопки', notes: null },
  { brand: 'Cryptocenter AI', platform: 'Website', region: 'Global', language: 'ru+en', handle: null,
    url: 'https://cryptocenter.finance', status: 'Confirmed', purpose: 'независимое криптомедиа, журнал',
    formats: 'статьи 3000–6000 зн.', accessOwner: A, hasAccess: true, apiKeyEnvName: null,
    priority: 'live', automationStatus: 'button', apiStatus: 'live',
    nextAction: 'publish.yml на main + секреты Actions', notes: '46 статей; фабрика на проде' },
  { brand: 'YLDX AI', platform: 'Website', region: 'Global', language: 'en', handle: null,
    url: 'https://yldx.ai', status: 'Confirmed', purpose: 'пресейл/продуктовый сайт',
    formats: null, accessOwner: A, hasAccess: true, apiKeyEnvName: null,
    priority: 'live', automationStatus: 'manual', apiStatus: 'none',
    nextAction: 'аудит №2 очереди (находки Центра: raised/audited)', notes: 'HANDS-OFF прод' },
  { brand: 'YLDX AI', platform: 'X', region: 'Global', language: 'en', handle: 'yldx_ai',
    url: null, status: 'Needs Verification', purpose: null, formats: null, accessOwner: null,
    hasAccess: null, apiKeyEnvName: null, priority: null, automationStatus: null, apiStatus: null,
    nextAction: 'подтвердить существование и владение', notes: 'из старого медиа-плана' },
  { brand: null, platform: 'Website', region: null, language: null, handle: null,
    url: 'https://sumerus.com', status: 'Needs Verification', purpose: null, formats: null, accessOwner: null,
    hasAccess: null, apiKeyEnvName: null, priority: null, automationStatus: null, apiStatus: null,
    nextAction: 'основатель: чей проект, включать ли в карту', notes: 'жив (DO), кабинет Connect Wallet' },
  { brand: 'Berg Mindset', platform: 'VK', region: 'RU', language: 'ru', handle: null,
    url: null, status: 'Not Registered', purpose: 'главный RU-хаб («Андрей Берг | Berg Mindset»)',
    formats: 'посты, статьи, клипы, эфиры', accessOwner: A, hasAccess: false, apiKeyEnvName: 'VK_TOKEN',
    priority: '1', automationStatus: 'fanout-ready', apiStatus: 'adapter-ready',
    nextAction: 'зарегистрировать сообщество + ключ API (право wall) → VK_TOKEN, VK_OWNER_ID',
    notes: 'preferred handle bergmindset — availability not verified; Berg Finance = рубрика, не отдельный аккаунт' },
  { brand: 'Berg Mindset', platform: 'Telegram', region: 'RU', language: 'ru', handle: null,
    url: null, status: 'Not Registered', purpose: 'личный RU-канал', formats: 'посты 600–900 зн.',
    accessOwner: A, hasAccess: false, apiKeyEnvName: 'REVIEW_BOT_TOKEN', priority: '2',
    automationStatus: 'button-ready', apiStatus: 'live',
    nextAction: 'создать канал, бота админом', notes: 'preferred handle bergmindset — availability not verified' },
  { brand: 'Berg Mindset', platform: 'RUTUBE', region: 'RU', language: 'ru', handle: null,
    url: null, status: 'Not Registered', purpose: 'видео-архив RU', formats: 'длинные + shorts',
    accessOwner: A, hasAccess: false, apiKeyEnvName: null, priority: '3', automationStatus: 'none',
    apiStatus: 'none', nextAction: 'регистрация; наполнение после видео-конвейера', notes: null },
  { brand: 'Berg Mindset', platform: 'Дзен', region: 'RU', language: 'ru', handle: null,
    url: null, status: 'Not Registered', purpose: 'статьи, SEO', formats: 'лонгриды',
    accessOwner: A, hasAccess: false, apiKeyEnvName: null, priority: '4', automationStatus: 'manual',
    apiStatus: 'none', nextAction: 'регистрация', notes: null },
  { brand: 'Berg Mindset', platform: 'MAX', region: 'RU', language: 'ru', handle: null,
    url: null, status: 'Not Registered', purpose: 'официальный канал, уведомления', formats: 'короткие',
    accessOwner: A, hasAccess: false, apiKeyEnvName: null, priority: '5', automationStatus: 'none',
    apiStatus: 'none', nextAction: 'регистрация', notes: 'бот/mini app позже, если доступно' },
  { brand: 'Berg Finance', platform: 'TradingView', region: 'Global', language: 'en', handle: null,
    url: null, status: 'Not Registered', purpose: 'Ideas, графические разборы', formats: 'графики, Pine',
    accessOwner: A, hasAccess: false, apiKeyEnvName: null, priority: '6', automationStatus: 'manual',
    apiStatus: 'none', nextAction: 'регистрация; Ideas ТОЛЬКО вручную до безопасного API',
    notes: 'preferred handle bergfinance — availability not verified' },
  { brand: 'Berg Mindset', platform: 'YouTube', region: 'Global', language: 'ru', handle: null,
    url: null, status: 'Planned', purpose: 'видео', formats: 'длинные + Shorts', accessOwner: A,
    hasAccess: false, apiKeyEnvName: null, priority: 'low', automationStatus: 'none', apiStatus: 'none',
    nextAction: 'после видео-конвейера', notes: 'галка altered/synthetic обязательна' },
  { brand: 'Berg Mindset', platform: 'TikTok', region: 'Global', language: 'ru+en', handle: null,
    url: null, status: 'Planned', purpose: 'расходный канал', formats: 'shorts', accessOwner: A,
    hasAccess: false, apiKeyEnvName: null, priority: 'low', automationStatus: 'none', apiStatus: 'none',
    nextAction: 'после видео-конвейера', notes: 'AI-плашки обязательны; крипто-реклама запрещена' },
  { brand: 'Berg Mindset', platform: 'Threads', region: 'Global', language: 'en', handle: null,
    url: null, status: 'Planned', purpose: null, formats: null, accessOwner: A, hasAccess: false,
    apiKeyEnvName: null, priority: 'low', automationStatus: 'none', apiStatus: 'none',
    nextAction: null, notes: null },
  // DeFiGuru — независимый контур (Operating Director = своя сессия); здесь только инвентарная запись.
  { brand: 'DeFiGuru', platform: 'Telegram (канал)', region: 'RU', language: 'ru', handle: '@defiguruinfoo',
    url: 'https://t.me/defiguruinfoo', status: 'Needs Verification',
    purpose: 'лента персонажа «DeFi Guru Channel» (канал-бродкаст, создан 03.08)',
    formats: 'мини-уроки 400–700 зн.', accessOwner: A, hasAccess: true, apiKeyEnvName: 'DEFIGURU_BOT_TOKEN',
    priority: 'high', automationStatus: 'button (@Defiguruaibot админ, can_post=true — проверено фактом; постилка перезапущена на канал)', apiStatus: 'live',
    nextAction: 'первый закреп кнопкой основателя (превью уже у него) → Confirmed по сигналу Operating Director',
    notes: '⚠️ t.me/defiguru — ЧУЖОЙ проект (defigur.us), не путать' },
  { brand: 'DeFiGuru', platform: 'Telegram (чат)', region: 'RU', language: 'ru', handle: '@defiguruinfo',
    url: 'https://t.me/defiguruinfo', status: 'Needs Verification',
    purpose: 'чат-обсуждение при канале (супергруппа)',
    formats: 'комьюнити', accessOwner: A, hasAccess: true, apiKeyEnvName: null,
    priority: 'medium', automationStatus: 'none', apiStatus: 'none',
    nextAction: 'привязать к каналу как discussion (в очереди у основателя) → Confirmed вместе с каналом',
    notes: 'связка канал+группа по медиа-канону' },
  { brand: 'DeFiGuru', platform: 'X', region: 'Global', language: 'en', handle: null,
    url: null, status: 'Not Registered', purpose: 'EN-контур персонажа', formats: 'треды/уроки',
    accessOwner: A, hasAccess: false, apiKeyEnvName: null, priority: 'high', automationStatus: 'none',
    apiStatus: 'none', nextAction: 'основатель регистрирует; постинг вручную до Blotato',
    notes: 'кандидат @DeFiGuruAI — availability not verified' },
]

// Очередь регистрации — порядок МОЙ (решение Медиа, утверждено основателем 02.08), Центр его не выводит.
export const QUEUE = [
  { order: 1, platform: 'ВКонтакте', brand: 'Berg Mindset', action: 'сообщество + ключ API (wall)', status: 'Not Registered' },
  { order: 2, platform: 'Telegram RU', brand: 'Berg Mindset', action: 'канал + бот админом', status: 'Not Registered' },
  { order: 3, platform: 'RUTUBE', brand: 'Berg Mindset', action: 'канал', status: 'Not Registered' },
  { order: 4, platform: 'Дзен', brand: 'Berg Mindset', action: 'канал статей', status: 'Not Registered' },
  { order: 5, platform: 'MAX', brand: 'Berg Mindset', action: 'официальный канал', status: 'Not Registered' },
  { order: 6, platform: 'TradingView', brand: 'Berg Finance', action: 'аккаунт; Ideas вручную', status: 'Not Registered' },
]

export function buildRegistry() {
  return {
    version: 1,
    generatedAt: new Date().toISOString(),
    dataAsOf: DATA_AS_OF, // дата последней правки ДАННЫХ (не время ответа) — для честной свежести
    source: 'media-backend',
    accounts: ACCOUNTS,
    queue: QUEUE,
  }
}
